# Taken from https://github.com/mperham/sidekiq/blob/master/examples/config.yml
# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: 5

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 8

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - critical
  - default
  - low
  - mailers

# You can override concurrency based on environment. However, it is best
# to let concurrency be dictated by RAILS_MAX_THREADS, see details here:
# https://gist.github.com/nateberkopec/2d1fcf77dc61e747438252e3895badf0
# production:
#   :concurrency: 10
